config/routes.rb
Rails.application.routes.draw do
  root 'loans#new'
  resources :loans do
    collection do
      get 'inspect'
    end
  end
end

app/models/loan.rb
class Loan < ActiveRecord::Base
  validates :amount, :ssn, :property_value, presence: true
  validate :loan_amount, :correct_ssn_format

  # validates that the loan amount is no more than the property value
  def loan_amount
    if amount.to_f > property_value.to_f
      errors.add(:amount,'loan amount may not be greater than the property value')
    end
  end

  # checks for false or non valid social security numbers
  def correct_ssn_format
    if (ssn =~ /(\d{3})[^\d]?(\d{2})[^\d]?(\d{4})/).nil?
      errors.add(:ssn, 'please enter a valid SSN')
    end
  end

  # calculates this loans loan to value
  def ltv
    (amount.to_f / property_value.to_f) * 100
  end

  # gives a use a reason why
  def reason
    why = ""
    if ltv > 40
      why << 'Loan amount too high for property value'
    end
    why
  end

  # outputs based on if this loan has been rejected or accepted
  def status_string
    if accepted?
      'Loan Accepted'
    else
      "Loan Rejected: #{reason}"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy]
  layout 'boot'
  # GET /loans
  # GET /loans.json
  def index
  end

  # GET /loans/1
  # GET /loans/1.json
  def show
  end

  # GET /loans/new
  def new
    # byebug
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans
  # POST /loans.json
  def create
    @loan = Loan.new(loan_params)
    @loan.amount = loan_params[:amount].gsub(/,/, '').to_f
    @loan.property_value = loan_params[:property_value].gsub(/,/, '').to_f

    if @loan.save
      # conduct first test for loan approval
      if @loan.ltv < 40
        @loan.update_attributes(:accepted => true)
      end
      redirect_to "/loans/#{@loan.id}"
    else
      flash[:error_hash] = @loan.errors.messages
      flash[:error] = @loan.errors.full_messages
      flash[:error_list] = @loan.errors.messages.keys
      redirect_to :back
    end
  end

  # Method to serve up a loan application status
  def inspect
    @loan = Loan.find_by_id(params[:search])
    if @loan
      render :partial => 'loan_present', :locals => { :loan => @loan }
    else
      render :html => "No loan application with id #{params[:search]}"
    end
  end

  # PATCH/PUT /loans/1
  # PATCH/PUT /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1
  # DELETE /loans/1.json
  def destroy
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_loan
      @loan = Loan.find(params[:id])
    end

    def loan_params
      params.fetch(:loan, {}).permit(:amount, :ssn, :property_value, :first_name, :last_name, :email, :phone, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ParksideLending</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/boot.html.erb
<link rel="stylesheet" href="/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="/css/overwrite.css">
<nav class="navbar navbar-default navbar-top">
  <div class="container">
    <ul class="nav nav-pills">
      <li>
        <a href="/" class='btn btn-primary btn-sm'>Apply For a New Loan</a>
      </li>
      <li>
        <a href="/loans" class='btn btn-primary btn-sm'>View Loan Status</a>
      </li>
    </ul>
  </div>
</nav>
<body>

  <div class="form-thin">
    <%= yield %>
  </div>

</body>

<script>
  setTimeout(function(){
    $('.error').fadeOut('1000');
  }, 3000)
</script>

app/views/loans/_form.html.erb
<%= form_for(@loan) do |f| %>
  <% if @loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
      <% @loan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/loans/_loan_present.html.erb
<div class="panel loan_show">
  <h2>Loan # <%= loan.id %></h2>
  <div class="panel loan_info">
    <b>Amount: </b>
    <%= number_to_currency(loan.amount) %>
    <br>
    <b>Property Value: </b>
    <%= number_to_currency(loan.property_value) %>
    <br>
    <b>Status</b>
    <div class="status <%= loan.accepted? ? 'accepted_application' : 'rejected_application' %>">
      <%= loan.status_string %>
      <br>
      Loan to Value Percentage: <%= loan.ltv %>%
    </div>
  </div>

  <div class="panel loan_info">
    <h4>Contact Information</h4>
    <b>Name: </b>
    <%= "#{loan.first_name} #{loan.last_name}" %>
    <br>
    <b>Email: </b>
    <%= loan.email %>
    <br>
    <b>Phone: </b>
    <%= loan.phone %>
    <br>
    <b>Notes: </b>
    <%= loan.description %>
    <br>
  </div>
</div>

app/views/loans/edit.html.erb
<h1>Editing Loan</h1>

<%= render 'form' %>

<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loans_path %>

app/views/loans/index.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
<p id="notice"><%= notice %></p>

<h1>View Loan Status</h1>
<form action="#" id='search-form-id' autocomplete="off">
  <div class="form-group">
    <input type="text" name='search' placeholder='Search by Application ID and press enter' class="form-control">
  </div>
</form>
<div class="progress_space"></div>

<!-- Modal -->
<div id="loanAppModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Loan Application</h4>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        You may press enter again to exit
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<script>
  // functionality for the id search bar
  $('body').on('submit', '#search-form-id', function(event) {
    event.preventDefault();
    var data = $(this).serialize();
    $(this).trigger('reset');
    $('.progress_space').html('<i class="fa fa-spinner fa-spin" style="font-size:24px"></i>Searching for Application')
    $.ajax({
      url: '/loans/inspect',
      data: data,
    })
    .done(function(data) {
      $('.modal-body').html(data);
      $('#loanAppModal').modal('show');
      $('.progress_space').html('');
    })

  });

  // enter submission for other browsers
  $('body').on('keydown', 'input[name="search"]', function(event) {
    if (event.which == 13) {
      event.preventDefault();
      if ($('#loanAppModal').css('display') == 'block') {
        $('button.close').trigger('click');
      } else{
        $('#search-form-id').trigger('submit');
      };
    };
  });
</script>

app/views/loans/new.html.erb
<h1>New Loan</h1>

<% if flash[:error].present? %>
  <div class="error">
    <ul>
      <% flash[:error].each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<form action="/loans" method='POST'>
<h3>Required Information</h3>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div class="form-group">
    <label for="loan[amount]">Loan Amount*</label>
    <input type="text" name='loan[amount]' class="form-control" required>
  </div>
  <div class="form-group">
    <label for="loan[property_value]">Property Value*</label>
    <input type="text" name='loan[property_value]' class="form-control" required>
  </div>
  <div class="form-group">
    <label for="loan[ssn]">Social Security Number*</label>
    <input type="text" name='loan[ssn]' class="form-control" required>
  </div>

  <h3>Additional Information</h3>
  <div class="form-group">
    <label for="loan[first_name]">First Name</label>
    <input type="text" name='loan[first_name]' class="form-control">
  </div>

  <div class="form-group">
    <label for="loan[last_name]">Last Name</label>
    <input type="text" name='loan[last_name]' class="form-control">
  </div>

  <div class="form-group">
    <label for="loan[email]">E-Mail</label>
    <input type="text" name='loan[email]' class="form-control">
  </div>

  <div class="form-group">
    <label for="loan[phone]">Phone</label>
    <input type="text" name='loan[phone]' class="form-control">
  </div>

  <div class="form-group">
    <label for="loan[description]">Notes</label>
    <textarea name="loan[description]" id="" cols="30" rows="10" class="form-control"></textarea>
  </div>


  <input type="submit" class='btn btn-lg btn-primary submit_button' value='Submit Application'>
</form>

<p>* required</p>

<% if flash[:error_list].present? %>
  <% flash[:error_list].each do |err| %>
    <script>
      $('input[name="loan[<%= err.to_s %>]"').addClass('erroneous')
      $('input[name="loan[<%= err.to_s %>]"').attr('placeholder', "<%= flash[:error_hash][err].join(', ').html_safe %>")
    </script>
  <% end %>
<% end %>

app/views/loans/show.html.erb
<h1>Completed Application</h1>
<%= render :partial => 'loan_present', :locals => { :loan => @loan } %>